# Welcome to Serverless!
---
service: insta
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  timeout: 30    # optional, in seconds, default is 6
  versionFunctions: false    # optional, default is true
  region: eu-central-1
  environment:
    SERVICE_NAME: ${self:service}
  profile: suka.yoga

plugins:

custom:

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  insta:
    handler: bin/insta
    events:
      - http:
          path: insta/{any+}
          method: get
    environment:
      USERNAME: ${file(./.env.yml):USERNAME}
      PASSWORD: ${file(./.env.yml):PASSWORD}
